name: tests

on: push

jobs:
  test:
    name: Run Tests with Python 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: echo "Project will be tested"
      - run: python --version 
      - run: pip install -r requirements.txt
      - run: pytest
