name: Tests with Docker

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Checkout code"
    - uses: actions/checkout@v4

    - run: echo "Set up Docker Buildx"
    - uses: docker/setup-buildx-action@v3

    - run: echo "Build Docker image"
    - run: docker build -t atlas_app:${{ github.sha }} .

    - run: echo "Install requirements for testing"
    - run: |
        docker run --rm \
          -e PYTHONPATH=/app/src:/app/tests \
          -w /app \
          atlas_app:${{ github.sha }} \
          pip install -r requirements.txt
    
    - run: echo "Run tests inside Docker container"
    - run: |
        docker run --rm \
          -e PYTHONPATH=/app/src:/app/tests \
          -w /app \
          atlas_app:${{ github.sha }} \
          sh -c "python -c 'import sys; print(sys.path); import atlas' && pytest"