name: Tests with Docker

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Checkout code"
    - uses: actions/checkout@v4

    - run: echo "Set up Docker Buildx"
    - uses: docker/setup-buildx-action@v3

    - run: echo "Build Docker image"
    - run: docker build -t atlas_app:${{ github.sha }} .

    - run: echo "Run tests inside Docker container"
    - run: |
        docker run --rm \
          -e PYTHONPATH=/app/src:/app/tests \
          atlas_app:${{ github.sha }} \
          pytest